[variables]
DEMUCS_PATH = '/opt/venv/bin/demucs'

[phases.setup]
nixPkgs = ['nodejs_22', 'python312', 'python312Packages.pip', 'ffmpeg', 'yt-dlp']

[phases.install]
cmds = [
  'npm ci',
  'python -m venv /opt/venv',
  '/opt/venv/bin/pip install --no-cache-dir --upgrade pip',
  '/opt/venv/bin/pip install --no-cache-dir -r requirements.txt'
]

[phases.build]
cmds = ['npm run build']

[start]
cmd = 'npm run start'
